// <auto-generated />
using System;
using GhumoOdisha.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhumoOdisha.Infrastructure.Migrations
{
    [DbContext(typeof(GhumoOdishaDbContext))]
    [Migration("20261004102903_TripPlacesCovered")]
    partial class TripPlacesCovered
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DestinationTrip", b =>
                {
                    b.Property<int>("DestinationsDestinationId")
                        .HasColumnType("int");

                    b.Property<int>("TripsTripId")
                        .HasColumnType("int");

                    b.HasKey("DestinationsDestinationId", "TripsTripId");

                    b.HasIndex("TripsTripId");

                    b.ToTable("TripDestinations", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.AdminActivity", b =>
                {
                    b.Property<long>("AdminActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AdminActivityId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.HasKey("AdminActivityId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Area", "TargetId");

                    b.ToTable("AdminActivities", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("AdminUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AdminUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.AppLog", b =>
                {
                    b.Property<long>("AppLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AppLogId"));

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<double?>("ElapsedMs")
                        .HasColumnType("double");

                    b.Property<string>("Exception")
                        .HasColumnType("mediumtext");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("AppLogId");

                    b.HasIndex("RequestId");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("Level", "TimestampUtc");

                    b.HasIndex("UserRole", "UserId", "TimestampUtc");

                    b.ToTable("AppLogs", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("AdvanceAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AmountPerPerson")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingNumber")
                        .HasColumnType("int");

                    b.Property<int>("BookingSource")
                        .HasColumnType("int");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("FemaleCount")
                        .HasColumnType("int");

                    b.Property<int?>("MaleCount")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingAdvanceAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PendingCouponCodeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingCouponDiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PendingDiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PickupPointId")
                        .HasColumnType("int");

                    b.Property<string>("RazorpayOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RazorpayPaymentId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RazorpayRefundId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("RefundWaived")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly?>("RemovedSlotEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RemovedSlotStartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("TripDateSlotId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingNumber")
                        .IsUnique();

                    b.HasIndex("BookingStatus");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("PickupPointId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("TripId");

                    b.HasIndex("CustomerId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("TripDateSlotId", "BookingStatus");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Booking_AdvanceAmount_NonNegative", "AdvanceAmount >= 0");

                            t.HasCheckConstraint("CK_Booking_GenderCounts", "COALESCE(MaleCount, 0) + COALESCE(FemaleCount, 0) <= NumberOfSeats");

                            t.HasCheckConstraint("CK_Booking_NumberOfSeats", "NumberOfSeats > 0");

                            t.HasCheckConstraint("CK_Booking_RemainingAmount", "RemainingAmount = GREATEST(TotalAmount - AdvanceAmount, 0)");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.BookingEvent", b =>
                {
                    b.Property<int>("BookingEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingEventId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisibleToCustomer")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("BookingEventId");

                    b.HasIndex("BookingId", "CreatedAt");

                    b.ToTable("BookingEvents", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.BookingPayment", b =>
                {
                    b.Property<int>("BookingPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingPaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("BookingPaymentId");

                    b.HasIndex("BookingId", "PaidAt");

                    b.ToTable("BookingPayments", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingPayment_Amount_Positive", "Amount > 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.BookingRefund", b =>
                {
                    b.Property<int>("BookingRefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingRefundId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("InitiatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BookingRefundId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("Status", "RequestedAt");

                    b.ToTable("BookingRefunds", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingRefunds_Amount", "Amount > 0 AND Amount <= AmountPaid");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.BookingTraveller", b =>
                {
                    b.Property<int>("BookingTravellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingTravellerId"));

                    b.Property<string>("AadhaarLast4")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedCustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BookingTravellerId");

                    b.HasIndex("LinkedCustomerId");

                    b.HasIndex("BookingId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("BookingTravellers", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingTraveller_AadhaarLast4", "AadhaarLast4 IS NULL OR CHAR_LENGTH(AadhaarLast4) = 4");

                            t.HasCheckConstraint("CK_BookingTraveller_SeatNumber", "SeatNumber > 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int?>("ActivePricingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BaseCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<bool>("HasAc")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("SubmittedForReviewAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CarId");

                    b.HasIndex("ActivePricingId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("Status", "BaseCity", "SeatCapacity");

                    b.ToTable("Cars", null, t =>
                        {
                            t.HasCheckConstraint("CK_Car_SeatCapacity", "SeatCapacity IN (5, 7, 9, 13, 15, 17, 20, 26)");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarAuditEvent", b =>
                {
                    b.Property<long>("CarAuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CarAuditEventId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("CarBookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisibleToCustomer")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.HasKey("CarAuditEventId");

                    b.HasIndex("CarBookingId", "CreatedAt");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("CarAuditEvents", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarBooking", b =>
                {
                    b.Property<int>("CarBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CarBookingId"));

                    b.Property<decimal?>("AdditionalCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("AdditionalChargesNote")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BalanceCollectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("BalanceDue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BookingAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingNumber")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CarPricingId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("DriverApproachKm")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<double?>("DropLatitude")
                        .HasColumnType("double");

                    b.Property<string>("DropLocation")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<double?>("DropLongitude")
                        .HasColumnType("double");

                    b.Property<int?>("DropToPickupKm")
                        .HasColumnType("int");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EstimatedBaseFare")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EstimatedKm")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedKmCharge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("EstimatedNightHaltCharge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EstimatedNights")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("FinalBaseFare")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("FinalKm")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalKmCharge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("FinalNightHaltCharge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("FinalNights")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("HoldExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("PickupAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PickupCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("PickupLatitude")
                        .HasColumnType("double");

                    b.Property<string>("PickupLocation")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<double?>("PickupLongitude")
                        .HasColumnType("double");

                    b.Property<int?>("PickupToDropKm")
                        .HasColumnType("int");

                    b.Property<string>("RazorpayOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RazorpayPaymentId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RazorpayRefundId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("RefundIssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RefundMethod")
                        .HasColumnType("int");

                    b.Property<string>("RefundReference")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("RefundSettledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReturnToBaseKm")
                        .HasColumnType("int");

                    b.Property<bool>("RoundTrip")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CarBookingId");

                    b.HasIndex("BookingNumber")
                        .IsUnique();

                    b.HasIndex("CarPricingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("DriverId", "Status");

                    b.HasIndex("CarId", "Status", "PickupAt", "EndsAt");

                    b.ToTable("CarBookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_CarBooking_AdditionalCharges", "AdditionalCharges IS NULL OR AdditionalCharges >= 0");

                            t.HasCheckConstraint("CK_CarBooking_BookingAmount", "BookingAmount >= 0");

                            t.HasCheckConstraint("CK_CarBooking_Duration", "DurationHours > 0");

                            t.HasCheckConstraint("CK_CarBooking_EstimatedKm", "EstimatedKm >= 0");

                            t.HasCheckConstraint("CK_CarBooking_EstimatedNights", "EstimatedNights >= 0");

                            t.HasCheckConstraint("CK_CarBooking_FinalKm", "FinalKm IS NULL OR FinalKm >= 0");

                            t.HasCheckConstraint("CK_CarBooking_Window", "EndsAt > PickupAt");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarPhoto", b =>
                {
                    b.Property<int>("CarPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CarPhotoId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.HasKey("CarPhotoId");

                    b.HasIndex("CarId", "Kind", "DisplayOrder");

                    b.ToTable("CarPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarPricing", b =>
                {
                    b.Property<int>("CarPricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CarPricingId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<decimal>("NightHaltPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PricePerKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SubmittedById")
                        .HasColumnType("int");

                    b.Property<string>("SubmittedByRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CarPricingId");

                    b.HasIndex("Status");

                    b.HasIndex("CarId", "Status");

                    b.ToTable("CarPricings", null, t =>
                        {
                            t.HasCheckConstraint("CK_CarPricing_NightHaltPrice", "NightHaltPrice >= 0");

                            t.HasCheckConstraint("CK_CarPricing_PricePerKm", "PricePerKm >= 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarPricingTier", b =>
                {
                    b.Property<int>("CarPricingTierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CarPricingTierId"));

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CarPricingId")
                        .HasColumnType("int");

                    b.Property<int?>("UpToKm")
                        .HasColumnType("int");

                    b.HasKey("CarPricingTierId");

                    b.HasIndex("CarPricingId", "UpToKm")
                        .IsUnique();

                    b.ToTable("CarPricingTiers", null, t =>
                        {
                            t.HasCheckConstraint("CK_CarPricingTier_BaseFare", "BaseFare >= 0");

                            t.HasCheckConstraint("CK_CarPricingTier_UpToKm", "UpToKm IS NULL OR UpToKm > 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarTripExecution", b =>
                {
                    b.Property<int>("CarTripExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CarTripExecutionId"));

                    b.Property<int?>("ActualKm")
                        .HasColumnType("int");

                    b.Property<int>("CarBookingId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EndLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("EndLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("EndOdometerKm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("NightHalts")
                        .HasColumnType("int");

                    b.Property<decimal?>("StartLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("StartLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("StartOdometerKm")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CarTripExecutionId");

                    b.HasIndex("CarBookingId")
                        .IsUnique();

                    b.HasIndex("DriverId", "CompletedAt");

                    b.ToTable("CarTripExecutions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CarTripExecution_ActualKm", "ActualKm IS NULL OR ActualKm = EndOdometerKm - StartOdometerKm");

                            t.HasCheckConstraint("CK_CarTripExecution_EndKm", "EndOdometerKm IS NULL OR EndOdometerKm >= StartOdometerKm");

                            t.HasCheckConstraint("CK_CarTripExecution_NightHalts", "NightHalts IS NULL OR NightHalts >= 0");

                            t.HasCheckConstraint("CK_CarTripExecution_StartKm", "StartOdometerKm >= 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CouponCode", b =>
                {
                    b.Property<int>("CouponCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CouponCodeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal>("CommissionPerSeat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFirstTimeCustomerOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("CouponCodeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CouponCodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CouponCode_CommissionPerSeat_NonNegative", "CommissionPerSeat >= 0");

                            t.HasCheckConstraint("CK_CouponCode_DiscountAmount_Positive", "DiscountAmount > 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CouponPayout", b =>
                {
                    b.Property<int>("CouponPayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CouponPayoutId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CouponCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CouponPayoutId");

                    b.HasIndex("CouponCodeId", "PaidAt");

                    b.ToTable("CouponPayouts", null, t =>
                        {
                            t.HasCheckConstraint("CK_CouponPayout_Amount_Positive", "Amount > 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CouponRedemption", b =>
                {
                    b.Property<int>("CouponRedemptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CouponRedemptionId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CouponCodeId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsNewCustomer")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CouponRedemptionId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CouponCodeId", "CustomerId")
                        .IsUnique();

                    b.ToTable("CouponRedemptions", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CustomerOtp", b =>
                {
                    b.Property<int>("CustomerOtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerOtpId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CustomerOtpId");

                    b.HasIndex("PhoneNumber", "IsUsed");

                    b.ToTable("CustomerOtps", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CustomerRefreshToken", b =>
                {
                    b.Property<int>("CustomerRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerRefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("CustomerRefreshTokenId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("CustomerRefreshTokens", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<string>("AboutText")
                        .HasColumnType("text");

                    b.Property<string>("BestSeason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("DistanceFromBhubaneswar")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IdealDuration")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KnownFor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Tagline")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DestinationId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<int?>("AddedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("BaseLatitude")
                        .HasColumnType("double");

                    b.Property<string>("BaseLocationLabel")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<double?>("BaseLongitude")
                        .HasColumnType("double");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DrivingLicenceNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("LicenceExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("SubmittedForReviewAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DriverId");

                    b.HasIndex("Email");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Drivers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Driver_ExperienceYears", "ExperienceYears IS NULL OR (ExperienceYears >= 0 AND ExperienceYears <= 60)");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.DriverDocument", b =>
                {
                    b.Property<int>("DriverDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DriverDocumentId"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("DriverDocumentId");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId", "CarId");

                    b.ToTable("DriverDocuments", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.DriverRefreshToken", b =>
                {
                    b.Property<int>("DriverRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DriverRefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("DriverRefreshTokenId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("DriverRefreshTokens", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryDay", b =>
                {
                    b.Property<int>("ItineraryDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItineraryDayId"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("ItineraryDayId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("ItineraryDays", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryPoint", b =>
                {
                    b.Property<int>("ItineraryPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItineraryPointId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ItineraryDayId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ItineraryPointId");

                    b.HasIndex("ItineraryDayId", "DisplayOrder");

                    b.ToTable("ItineraryPoints", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.OrganizerPhoto", b =>
                {
                    b.Property<int>("OrganizerPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrganizerPhotoId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrganizerPhotoId");

                    b.ToTable("OrganizerPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.PaymentQrCode", b =>
                {
                    b.Property<int>("PaymentQrCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentQrCodeId"));

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PaymentQrCodeId");

                    b.ToTable("PaymentQrCodes", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.PickupPoint", b =>
                {
                    b.Property<int>("PickupPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PickupPointId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("PickupPointId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("PickupPoints", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.RoomPhoto", b =>
                {
                    b.Property<int>("RoomPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomPhotoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("RoomPhotoId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("RoomPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.SearchLog", b =>
                {
                    b.Property<long>("SearchLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SearchLogId"));

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Place")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ResultCount")
                        .HasColumnType("int");

                    b.HasKey("SearchLogId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Month", "CreatedAtUtc");

                    b.HasIndex("Place", "CreatedAtUtc");

                    b.ToTable("SearchLogs", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ServiceArea", b =>
                {
                    b.Property<int>("ServiceAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ServiceAreaId"));

                    b.Property<string>("BoundaryJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pincodes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ServiceAreaId");

                    b.HasIndex("IsActive");

                    b.ToTable("ServiceAreas", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.SiteHeroPhoto", b =>
                {
                    b.Property<int>("SiteHeroPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SiteHeroPhotoId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SiteHeroPhotoId");

                    b.HasIndex("Page")
                        .IsUnique();

                    b.ToTable("SiteHeroPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TermsAcceptance", b =>
                {
                    b.Property<int>("TermsAcceptanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TermsAcceptanceId"));

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("TermsAcceptanceId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("TermsAcceptances", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripId"));

                    b.Property<bool>("AllowCoupons")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("AmountPerPerson")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IncludesAcVehicle")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesBonfire")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesBreakfast")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesCamping")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesCoordinator")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesDinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesLunch")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesMusicalNight")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesPushbackVehicle")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesStay")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesSwimmingPool")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItineraryPdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PlacesCovered")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TripId");

                    b.HasIndex("Status");

                    b.ToTable("Trips", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trip_AmountPerPerson", "AmountPerPerson >= 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripDateSlot", b =>
                {
                    b.Property<int>("TripDateSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripDateSlotId"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TripDateSlotId");

                    b.HasIndex("Status");

                    b.HasIndex("TripId", "StartDate");

                    b.ToTable("TripDateSlots", null, t =>
                        {
                            t.HasCheckConstraint("CK_TripDateSlot_AvailableSeats_LteTotal", "AvailableSeats <= TotalSeats");

                            t.HasCheckConstraint("CK_TripDateSlot_AvailableSeats_NonNegative", "AvailableSeats >= 0");

                            t.HasCheckConstraint("CK_TripDateSlot_EndDate", "EndDate >= StartDate");

                            t.HasCheckConstraint("CK_TripDateSlot_TotalSeats", "TotalSeats > 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripHighlight", b =>
                {
                    b.Property<int>("TripHighlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripHighlightId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("TripHighlightId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("TripHighlights", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripPhoto", b =>
                {
                    b.Property<int>("TripPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripPhotoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("TripPhotoId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("TripPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.VehiclePhoto", b =>
                {
                    b.Property<int>("VehiclePhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VehiclePhotoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("VehiclePhotoId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("VehiclePhotos", (string)null);
                });

            modelBuilder.Entity("DestinationTrip", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationsDestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripsTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Booking", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.PickupPoint", "PickupPoint")
                        .WithMany()
                        .HasForeignKey("PickupPointId");

                    b.HasOne("GhumoOdisha.Domain.Entities.TripDateSlot", "TripDateSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("TripDateSlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PickupPoint");

                    b.Navigation("Trip");

                    b.Navigation("TripDateSlot");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.BookingEvent", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Booking", "Booking")
                        .WithMany("Events")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.BookingPayment", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.BookingRefund", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Booking", "Booking")
                        .WithOne("Refund")
                        .HasForeignKey("GhumoOdisha.Domain.Entities.BookingRefund", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.BookingTraveller", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Booking", "Booking")
                        .WithMany("Travellers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "LinkedCustomer")
                        .WithMany()
                        .HasForeignKey("LinkedCustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("LinkedCustomer");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Car", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.CarPricing", "ActivePricing")
                        .WithMany()
                        .HasForeignKey("ActivePricingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GhumoOdisha.Domain.Entities.Driver", "Driver")
                        .WithMany("Cars")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivePricing");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarBooking", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Car", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.CarPricing", "CarPricing")
                        .WithMany()
                        .HasForeignKey("CarPricingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CarPricing");

                    b.Navigation("Customer");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarPhoto", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Car", "Car")
                        .WithMany("Photos")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarPricing", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Car", "Car")
                        .WithMany("Pricings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarPricingTier", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.CarPricing", "CarPricing")
                        .WithMany("Tiers")
                        .HasForeignKey("CarPricingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarPricing");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarTripExecution", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.CarBooking", "CarBooking")
                        .WithOne("Execution")
                        .HasForeignKey("GhumoOdisha.Domain.Entities.CarTripExecution", "CarBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBooking");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CouponPayout", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.CouponCode", "CouponCode")
                        .WithMany("Payouts")
                        .HasForeignKey("CouponCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CouponCode");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CouponRedemption", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.CouponCode", "CouponCode")
                        .WithMany("Redemptions")
                        .HasForeignKey("CouponCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("CouponCode");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CustomerRefreshToken", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.DriverDocument", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GhumoOdisha.Domain.Entities.Driver", "Driver")
                        .WithMany("Documents")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.DriverRefreshToken", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Driver", "Driver")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryDay", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("ItineraryDays")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryPoint", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.ItineraryDay", "ItineraryDay")
                        .WithMany("ItineraryPoints")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.PickupPoint", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("PickupPoints")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.RoomPhoto", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("RoomPhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TermsAcceptance", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripDateSlot", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("TripDateSlots")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripHighlight", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("TripHighlights")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripPhoto", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("TripPhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.VehiclePhoto", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("VehiclePhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Payments");

                    b.Navigation("Refund");

                    b.Navigation("Travellers");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Car", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Photos");

                    b.Navigation("Pricings");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarBooking", b =>
                {
                    b.Navigation("Execution");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CarPricing", b =>
                {
                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CouponCode", b =>
                {
                    b.Navigation("Payouts");

                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Documents");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryDay", b =>
                {
                    b.Navigation("ItineraryPoints");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ItineraryDays");

                    b.Navigation("PickupPoints");

                    b.Navigation("RoomPhotos");

                    b.Navigation("TripDateSlots");

                    b.Navigation("TripHighlights");

                    b.Navigation("TripPhotos");

                    b.Navigation("VehiclePhotos");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripDateSlot", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
