// <auto-generated />
using System;
using GhumoOdisha.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhumoOdisha.Infrastructure.Migrations
{
    [DbContext(typeof(GhumoOdishaDbContext))]
    [Migration("20260924220225_AddTripsHeroAndDestinationCover")]
    partial class AddTripsHeroAndDestinationCover
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DestinationTrip", b =>
                {
                    b.Property<int>("DestinationsDestinationId")
                        .HasColumnType("int");

                    b.Property<int>("TripsTripId")
                        .HasColumnType("int");

                    b.HasKey("DestinationsDestinationId", "TripsTripId");

                    b.HasIndex("TripsTripId");

                    b.ToTable("TripDestinations", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("AdminUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AdminUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("AdvanceAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AmountPerPerson")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingSource")
                        .HasColumnType("int");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingAdvanceAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PendingCouponCodeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingCouponDiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PendingDiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PickupPointId")
                        .HasColumnType("int");

                    b.Property<string>("RazorpayOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RazorpayPaymentId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RazorpayRefundId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TripDateSlotId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingStatus");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("PickupPointId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("TripId");

                    b.HasIndex("CustomerId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("TripDateSlotId", "BookingStatus");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Booking_AdvanceAmount_LteTotal", "AdvanceAmount <= TotalAmount");

                            t.HasCheckConstraint("CK_Booking_AdvanceAmount_NonNegative", "AdvanceAmount >= 0");

                            t.HasCheckConstraint("CK_Booking_NumberOfSeats", "NumberOfSeats > 0");

                            t.HasCheckConstraint("CK_Booking_RemainingAmount", "RemainingAmount = TotalAmount - AdvanceAmount");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CouponCode", b =>
                {
                    b.Property<int>("CouponCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CouponCodeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal>("CommissionPerSeat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFirstTimeCustomerOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("CouponCodeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CouponCodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CouponCode_CommissionPerSeat_NonNegative", "CommissionPerSeat >= 0");

                            t.HasCheckConstraint("CK_CouponCode_DiscountAmount_Positive", "DiscountAmount > 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CouponRedemption", b =>
                {
                    b.Property<int>("CouponRedemptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CouponRedemptionId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CouponCodeId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsNewCustomer")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CouponRedemptionId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CouponCodeId", "CustomerId")
                        .IsUnique();

                    b.ToTable("CouponRedemptions", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PinHash")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CustomerOtp", b =>
                {
                    b.Property<int>("CustomerOtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerOtpId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CustomerOtpId");

                    b.HasIndex("PhoneNumber", "IsUsed");

                    b.ToTable("CustomerOtps", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CustomerRefreshToken", b =>
                {
                    b.Property<int>("CustomerRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerRefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("CustomerRefreshTokenId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("CustomerRefreshTokens", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<string>("AboutText")
                        .HasColumnType("text");

                    b.Property<string>("BestSeason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("DistanceFromBhubaneswar")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IdealDuration")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KnownFor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Tagline")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DestinationId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryDay", b =>
                {
                    b.Property<int>("ItineraryDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItineraryDayId"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("ItineraryDayId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("ItineraryDays", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryPoint", b =>
                {
                    b.Property<int>("ItineraryPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItineraryPointId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ItineraryDayId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ItineraryPointId");

                    b.HasIndex("ItineraryDayId", "DisplayOrder");

                    b.ToTable("ItineraryPoints", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.OrganizerPhoto", b =>
                {
                    b.Property<int>("OrganizerPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrganizerPhotoId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrganizerPhotoId");

                    b.ToTable("OrganizerPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.PickupPoint", b =>
                {
                    b.Property<int>("PickupPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PickupPointId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("PickupPointId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("PickupPoints", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.RoomPhoto", b =>
                {
                    b.Property<int>("RoomPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomPhotoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("RoomPhotoId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("RoomPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.SiteHeroPhoto", b =>
                {
                    b.Property<int>("SiteHeroPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SiteHeroPhotoId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SiteHeroPhotoId");

                    b.HasIndex("Page")
                        .IsUnique();

                    b.ToTable("SiteHeroPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TermsAcceptance", b =>
                {
                    b.Property<int>("TermsAcceptanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TermsAcceptanceId"));

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("TermsAcceptanceId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("TermsAcceptances", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripId"));

                    b.Property<decimal>("AmountPerPerson")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IncludesBreakfast")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesCoordinator")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesDinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesLunch")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesStay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItineraryPdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TripId");

                    b.HasIndex("Status");

                    b.ToTable("Trips", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trip_AmountPerPerson", "AmountPerPerson >= 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripDateSlot", b =>
                {
                    b.Property<int>("TripDateSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripDateSlotId"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TripDateSlotId");

                    b.HasIndex("Status");

                    b.HasIndex("TripId", "StartDate");

                    b.ToTable("TripDateSlots", null, t =>
                        {
                            t.HasCheckConstraint("CK_TripDateSlot_AvailableSeats_LteTotal", "AvailableSeats <= TotalSeats");

                            t.HasCheckConstraint("CK_TripDateSlot_AvailableSeats_NonNegative", "AvailableSeats >= 0");

                            t.HasCheckConstraint("CK_TripDateSlot_EndDate", "EndDate >= StartDate");

                            t.HasCheckConstraint("CK_TripDateSlot_TotalSeats", "TotalSeats > 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripHighlight", b =>
                {
                    b.Property<int>("TripHighlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripHighlightId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("TripHighlightId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("TripHighlights", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripPhoto", b =>
                {
                    b.Property<int>("TripPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripPhotoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("TripPhotoId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("TripPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.VehiclePhoto", b =>
                {
                    b.Property<int>("VehiclePhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VehiclePhotoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("VehiclePhotoId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("VehiclePhotos", (string)null);
                });

            modelBuilder.Entity("DestinationTrip", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationsDestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripsTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Booking", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.PickupPoint", "PickupPoint")
                        .WithMany()
                        .HasForeignKey("PickupPointId");

                    b.HasOne("GhumoOdisha.Domain.Entities.TripDateSlot", "TripDateSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("TripDateSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PickupPoint");

                    b.Navigation("Trip");

                    b.Navigation("TripDateSlot");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CouponRedemption", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.CouponCode", "CouponCode")
                        .WithMany("Redemptions")
                        .HasForeignKey("CouponCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("CouponCode");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CustomerRefreshToken", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryDay", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("ItineraryDays")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryPoint", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.ItineraryDay", "ItineraryDay")
                        .WithMany("ItineraryPoints")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.PickupPoint", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("PickupPoints")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.RoomPhoto", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("RoomPhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TermsAcceptance", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripDateSlot", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("TripDateSlots")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripHighlight", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("TripHighlights")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripPhoto", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("TripPhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.VehiclePhoto", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("VehiclePhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CouponCode", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryDay", b =>
                {
                    b.Navigation("ItineraryPoints");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ItineraryDays");

                    b.Navigation("PickupPoints");

                    b.Navigation("RoomPhotos");

                    b.Navigation("TripDateSlots");

                    b.Navigation("TripHighlights");

                    b.Navigation("TripPhotos");

                    b.Navigation("VehiclePhotos");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripDateSlot", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
