// <auto-generated />
using System;
using GhumoOdisha.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhumoOdisha.Infrastructure.Migrations
{
    [DbContext(typeof(GhumoOdishaDbContext))]
    [Migration("20260920102624_AddCustomerOtpAndRefreshTokens")]
    partial class AddCustomerOtpAndRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("AdminUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AdminUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("AdvanceAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AmountPerPerson")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingSource")
                        .HasColumnType("int");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TripDateSlotId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingStatus");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("TripId");

                    b.HasIndex("CustomerId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("TripDateSlotId", "BookingStatus");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Booking_AdvanceAmount_LteTotal", "AdvanceAmount <= TotalAmount");

                            t.HasCheckConstraint("CK_Booking_AdvanceAmount_NonNegative", "AdvanceAmount >= 0");

                            t.HasCheckConstraint("CK_Booking_NumberOfSeats", "NumberOfSeats > 0");

                            t.HasCheckConstraint("CK_Booking_RemainingAmount", "RemainingAmount = TotalAmount - AdvanceAmount");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PinHash")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CustomerOtp", b =>
                {
                    b.Property<int>("CustomerOtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerOtpId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CustomerOtpId");

                    b.HasIndex("PhoneNumber", "IsUsed");

                    b.ToTable("CustomerOtps", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CustomerRefreshToken", b =>
                {
                    b.Property<int>("CustomerRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerRefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("CustomerRefreshTokenId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("CustomerRefreshTokens", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryDay", b =>
                {
                    b.Property<int>("ItineraryDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItineraryDayId"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("ItineraryDayId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("ItineraryDays", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryPoint", b =>
                {
                    b.Property<int>("ItineraryPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItineraryPointId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ItineraryDayId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ItineraryPointId");

                    b.HasIndex("ItineraryDayId", "DisplayOrder");

                    b.ToTable("ItineraryPoints", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.RoomPhoto", b =>
                {
                    b.Property<int>("RoomPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomPhotoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("RoomPhotoId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("RoomPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripId"));

                    b.Property<decimal>("AmountPerPerson")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IncludesBreakfast")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesCoordinator")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesDinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesLunch")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludesStay")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TripId");

                    b.HasIndex("Status");

                    b.ToTable("Trips", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trip_AmountPerPerson", "AmountPerPerson >= 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripDateSlot", b =>
                {
                    b.Property<int>("TripDateSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripDateSlotId"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TripDateSlotId");

                    b.HasIndex("Status");

                    b.HasIndex("TripId", "StartDate");

                    b.ToTable("TripDateSlots", null, t =>
                        {
                            t.HasCheckConstraint("CK_TripDateSlot_AvailableSeats_LteTotal", "AvailableSeats <= TotalSeats");

                            t.HasCheckConstraint("CK_TripDateSlot_AvailableSeats_NonNegative", "AvailableSeats >= 0");

                            t.HasCheckConstraint("CK_TripDateSlot_EndDate", "EndDate >= StartDate");

                            t.HasCheckConstraint("CK_TripDateSlot_TotalSeats", "TotalSeats > 0");
                        });
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripHighlight", b =>
                {
                    b.Property<int>("TripHighlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripHighlightId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("TripHighlightId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("TripHighlights", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripPhoto", b =>
                {
                    b.Property<int>("TripPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TripPhotoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("TripPhotoId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.ToTable("TripPhotos", (string)null);
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Booking", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.TripDateSlot", "TripDateSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("TripDateSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Trip");

                    b.Navigation("TripDateSlot");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.CustomerRefreshToken", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Customer", "Customer")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryDay", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("ItineraryDays")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryPoint", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.ItineraryDay", "ItineraryDay")
                        .WithMany("ItineraryPoints")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.RoomPhoto", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("RoomPhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripDateSlot", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("TripDateSlots")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripHighlight", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("TripHighlights")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripPhoto", b =>
                {
                    b.HasOne("GhumoOdisha.Domain.Entities.Trip", "Trip")
                        .WithMany("TripPhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.ItineraryDay", b =>
                {
                    b.Navigation("ItineraryPoints");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ItineraryDays");

                    b.Navigation("RoomPhotos");

                    b.Navigation("TripDateSlots");

                    b.Navigation("TripHighlights");

                    b.Navigation("TripPhotos");
                });

            modelBuilder.Entity("GhumoOdisha.Domain.Entities.TripDateSlot", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
